"""Prepare the expanded-mHC capture derivative of the precision release image (local, no build, no nodes).

Writes, from kit inputs only and reproducibly:
  claude-mhc-expanded-model.py     the release DS4.1 model (engram-progress-model.py, byte-equal to the
                                   release lock's vllm/models/deepseek_v4_1/nvidia/model.py) plus one
                                   import and one install(self) call at the end of DeepseekV4Model.__init__,
                                   the activation-trace image's reviewed anchors
  Dockerfile.claude-mhc-expanded   FROM the release image; one COPY, one RUN of the installer; the release
                                   environment (cache namespaces included) is inherited unchanged, so the
                                   seeded selection roots and the release environment gates apply as-is
  claude-mhc-expanded.lock.json    inputs, targets (pre/post images), base identity and kind

    .venv-snapshot-cpu/bin/python claude-mhc-expanded-prepare.py [--check]

--check verifies the committed outputs equal a fresh preparation and writes nothing.
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
KIND = 'mhc-expanded-capture'
BASE_IMAGE = '1989e16daf38d2966b03a2e2abcb878263fb7d17183c8d6c5b084a51fbed7e8f'
BASE_LOCK = 'ds41-precision-release.lock.json'
BASE_LOCK_SHA256 = '4b1afffe455d634cbadc82353a64beb3c96bbaf89b595c948c00dbfa3b1f1c32'
BASE_KIND = 'precision-release-candidate'
INSTALL_DIR = '/opt/ds41-mhc-expanded'
MODEL_TARGET = 'vllm/vllm/models/deepseek_v4_1/nvidia/model.py'
HELPER_TARGET = 'vllm/vllm/models/deepseek_v4_1/claude_mhc_expanded.py'
BASE_MODEL = 'engram-progress-model.py'
IMPORT_ANCHOR = 'from b12x.sequence import engram as engram_native\n'
IMPORT_LINES = ('# DIAGNOSTIC ONLY: expanded mHC capture on the decision forward (claude_mhc_expanded.py).\n'
                'import vllm.models.deepseek_v4_1.claude_mhc_expanded as _mhc_expanded\n')
INIT_ANCHOR = '        else:\n            self._mtp_hidden_buffer = None\n'
INIT_LINES = ('        # DIAGNOSTIC ONLY: wraps engram layers\' mHC pre; nothing is allocated or copied\n'
              '        # until /cache/claude-mhc-expanded.json arms one decision forward.\n'
              '        _mhc_expanded.install(self)\n')
INPUTS = ('Dockerfile.claude-mhc-expanded', 'claude-mhc-expanded-capture.py', 'claude-mhc-expanded-install.py',
          'claude-mhc-expanded-model.py')
OUTPUTS = ('claude-mhc-expanded-model.py', 'Dockerfile.claude-mhc-expanded', 'claude-mhc-expanded.lock.json')


def sha(data):
    return hashlib.sha256(data).hexdigest()


def model_source(base):
    for anchor in (IMPORT_ANCHOR, INIT_ANCHOR):
        if base.count(anchor) != 1:
            raise RuntimeError('Model anchor is not unique: ' + anchor.strip())
    return base.replace(IMPORT_ANCHOR, IMPORT_ANCHOR + IMPORT_LINES).replace(INIT_ANCHOR, INIT_ANCHOR + INIT_LINES)


def dockerfile():
    return (
        '# DIAGNOSTIC ONLY. Never a serving candidate: the precision release image plus a capture of the\n'
        '# expanded mHC pre inputs and served outputs on engram layers (claude-mhc-expanded-capture.py).\n'
        '# Copies only, no arithmetic change; the release environment is inherited unchanged.\n'
        '# Generated by claude-mhc-expanded-prepare.py.\n'
        f'FROM {BASE_IMAGE}\n'
        'ARG MHC_EXPANDED_LOCK\n'
        f'COPY {" ".join(sorted(INPUTS))} claude-mhc-expanded.lock.json {INSTALL_DIR}/\n'
        f'RUN /opt/venv/bin/python {INSTALL_DIR}/claude-mhc-expanded-install.py\n'
        f'LABEL local-inference.ds41.diagnostic.kind="{KIND}" \\\n'
        '    local-inference.ds41.diagnostic.lock.sha256="${MHC_EXPANDED_LOCK}" \\\n'
        f'    local-inference.ds41.diagnostic.base-image="{BASE_IMAGE}" \\\n'
        f'    local-inference.ds41.diagnostic.base-kind="{BASE_KIND}" \\\n'
        f'    local-inference.ds41.diagnostic.base-lock.sha256="{BASE_LOCK_SHA256}" \\\n'
        '    vllm.source-tree="release-0a446838-plus-claude-mhc-expanded-see-lock" \\\n'
        '    local-inference.status="diagnostic-only-not-qualified" \\\n'
        '    org.opencontainers.image.title="DS4.1 precision release with expanded mHC capture diagnostic"\n')


def memory_plan(root=ROOT):
    """The helper's own exact per-rank plan for the DS4.1 TP4 shape (hidden 5120, 8192 rows, four ranks)."""
    import importlib.util
    spec = importlib.util.spec_from_file_location('claude_mhc_expanded_plan', root / 'claude-mhc-expanded-capture.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return {'hidden': 5120, 'rows': module.CHUNK_ROWS, **module.memory_plan(5120, module.CHUNK_ROWS, 4)}


def lock(root=ROOT, generated=None):
    generated = generated or {}
    read = lambda name: generated[name] if name in generated else (root / name).read_bytes()
    base_lock = (root / BASE_LOCK).read_bytes()
    if sha(base_lock) != BASE_LOCK_SHA256:
        raise RuntimeError('Release lock changed')
    release = json.loads(base_lock)
    model_before = release['after']['vllm']['vllm/models/deepseek_v4_1/nvidia/model.py']['sha256']
    if sha((root / BASE_MODEL).read_bytes()) != model_before:
        raise RuntimeError(f'{BASE_MODEL} is not the release model')
    if 'vllm/models/deepseek_v4_1/claude_mhc_expanded.py' in release['after']['vllm']:
        raise RuntimeError('Release already carries the capture helper')
    return {
        'kind': KIND, 'image_kind_label': KIND, 'status': 'diagnostic-only-not-built-not-qualified',
        'scope': ('expanded mHC pre inputs and served outputs on engram layers of the decision forward; '
                  'adds copies after producers; operator evidence only, not a serving or numerical-policy input'),
        'base_image_id': BASE_IMAGE, 'base_kind': BASE_KIND, 'base_lock': BASE_LOCK,
        'base_lock_sha256': BASE_LOCK_SHA256, 'base_trees': release['trees'],
        'base_inventory': '/opt/ds41-precision-release/preserved-files.json', 'install_dir': INSTALL_DIR,
        'install_pass_marker': 'MHC-EXPANDED-INSTALL-PASS', 'capture_schema': 'claude-mhc-expanded-v2',
        'memory_plan': memory_plan(root),
        'build_args': ['MHC_EXPANDED_LOCK'],
        'inputs': {name: sha(read(name)) for name in sorted(INPUTS)},
        'targets': {MODEL_TARGET: {'source': 'claude-mhc-expanded-model.py', 'input_sha256': model_before,
                                   'output_sha256': sha(read('claude-mhc-expanded-model.py'))},
                    HELPER_TARGET: {'source': 'claude-mhc-expanded-capture.py', 'input_sha256': None,
                                    'output_sha256': sha(read('claude-mhc-expanded-capture.py'))}},
    }


def prepare(root=ROOT):
    """{output name: bytes} of a fresh preparation."""
    out = {'claude-mhc-expanded-model.py': model_source((root / BASE_MODEL).read_text()).encode(),
           'Dockerfile.claude-mhc-expanded': dockerfile().encode()}
    out['claude-mhc-expanded.lock.json'] = (json.dumps(lock(root, out), indent=1, sort_keys=True) + '\n').encode()
    return out


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--check', action='store_true')
    a = p.parse_args()
    fresh = prepare()
    if a.check:
        stale = [n for n, data in fresh.items() if not (ROOT / n).is_file() or (ROOT / n).read_bytes() != data]
        if stale:
            raise SystemExit('Stale prepared outputs: ' + ', '.join(stale))
    else:
        for name, data in fresh.items():
            (ROOT / name).write_bytes(data)
    print('MHC-EXPANDED-PREPARED', sha(fresh['claude-mhc-expanded.lock.json']), flush=True)


if __name__ == '__main__':
    main()
