"""Freeze the clean precision release derivative of the router parent e06df11a (no capture helpers).

Review artifact only: no build, node, GPU or launch. The only source delta over the router
stage-release candidate (lock 7122753a, trees vllm ce1b9bcd / b12x 03a4e0b3) is the
worker-wide BF16 reduced-precision disable already tested in the precision capture arms:

  vllm/v1/worker/gpu_worker.py     router bytes e41fa1f4 -> the exact tested hooked worker
  vllm/v1/worker/ds41_precision.py new, the exact tested helper

Both files are byte-identical to the precision capture image's targets (lock 541ba799), so
the release carries the arithmetic that was evaluated, minus attention.py capture edits and
the three capture helpers, which the router parent never had. B12X and every native
artifact stay the router's; the installer proves the image inventory delta is exactly
those two paths. The router's own GPU gates (engram, router prefill, ring) are reused
unchanged, plus a precision smoke.

Usage (local, no nodes): python3 ds41_precision_release_prepare.py
Outputs: ds41-precision-release.lock.json, ds41-precision-release.ignore,
Dockerfile.ds41-precision-release. Install dir /opt/ds41-precision-release, install
marker PRECISION-RELEASE-INSTALL-PASS, kind label precision-release-candidate.
"""
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))
import prepare as _runtime_prepare  # noqa: E402,F401  (puts the parent kit, with contracts.py, on sys.path)
STEM = 'ds41-precision-release'
KIND = 'precision-release-candidate'
STATUS = 'candidate-not-qualified'
INSTALL_DIR = '/opt/ds41-precision-release'
INSTALL_PASS = 'PRECISION-RELEASE-INSTALL-PASS'
SMOKE_PASS = 'PRECISION-RELEASE-SMOKE-PASS'
ROUTER_LOCK = 'router-release.lock.json'
ROUTER_RECEIPT = 'receipts/router-release-build-receipt.json'
PRECISION_LOCK = 'ds41-precision.lock.json'
WORKER = 'vllm/v1/worker/gpu_worker.py'
HELPER = 'vllm/v1/worker/ds41_precision.py'
SOURCES = {WORKER: 'ds41-precision-gpu_worker.py', HELPER: 'ds41_precision.py'}
# Paths that must never exist in the release (capture instrumentation of the diagnostic lineage).
CAPTURE_PATHS = ('vllm/models/deepseek_v4_1/claude_decision_row.py', 'vllm/models/deepseek_v4_1/claude_window.py',
                 'vllm/models/deepseek_v4_1/ds41_indexer_capture.py')
# The router build's GPU gates and their data, reused byte for byte (checked against the router lock).
GATES = (('verify_engram_repair.py', 'ENGRAM-NATIVE-GATE-PASS'),
         ('test_router_prefill_gpu.py', 'ROUTER-PREFILL-GPU-PASS cases=4'),
         ('test_engram_epoch_gpu.py', 'ENGRAM-EPOCH-GPU-PASS 8'),
         ('test_engram_enqueue_gpu.py', 'ENGRAM-ENQUEUE-GPU-PASS 16'),
         ('run_ring_regression.py', 'RING-REGRESSION-PASS cases=29'))
GATE_DATA = ('engram-progress-engram.py', 'test_compressor_ring_mapping.py', 'seccomp-io-uring.json')
PACKAGED = ('ds41_precision_release_prepare.py', 'ds41_precision_release_install.py',
            'ds41_precision_release_smoke.py', 'build_precision_release.py', 'test_ds41_precision_release.py',
            'Dockerfile.' + STEM, *SOURCES.values(), *(g for g, _ in GATES), *GATE_DATA)

DOCKERFILE = """# Precision release CANDIDATE (not qualified): router stage-release parent {short} plus the
# worker-wide BF16 reduced-precision disable only. No capture helpers or diagnostic pins.
# Generated by ds41_precision_release_prepare.py.
FROM {base}
ARG PRECISION_LOCK
ARG PRECISION_CACHE
COPY {copy} {install}/
RUN /opt/venv/bin/python {install}/ds41_precision_release_install.py
ENV XDG_CACHE_HOME=/cache/jit/${{PRECISION_CACHE}} \\
    VLLM_CACHE_ROOT=/cache/jit/${{PRECISION_CACHE}}/vllm \\
    TORCHINDUCTOR_CACHE_DIR=/cache/jit/${{PRECISION_CACHE}}/inductor \\
    TRITON_CACHE_DIR=/cache/jit/${{PRECISION_CACHE}}/triton \\
    B12X_COMPILE_CACHE_DIR=/cache/jit/${{PRECISION_CACHE}}/b12x \\
    B12X_CUTE_COMPILE_CACHE_DIR=/cache/jit/${{PRECISION_CACHE}}/b12x/cute \\
    SPARKINFER_COMPILE_CACHE_DIR=/cache/jit/${{PRECISION_CACHE}}/b12x/compile \\
    CUTE_DSL_CACHE_DIR=/cache/jit/${{PRECISION_CACHE}}/cute-dsl
LABEL local-inference.ds41.diagnostic.kind="{kind}" \\
    local-inference.ds41.diagnostic.lock.sha256="${{PRECISION_LOCK}}" \\
    local-inference.ds41.release.base-image="{base}" \\
    local-inference.ds41.release.base-lock.sha256="{base_lock}" \\
    local-inference.ds41.release.precision-lock.sha256="{precision_lock}" \\
    local-inference.cache.fingerprint="${{PRECISION_CACHE}}" \\
    vllm.source-tree="{vllm}" \\
    b12x.source-tree="{b12x}" \\
    local-inference.status="{status}" \\
    org.opencontainers.image.title="DS4.1 router stage-release plus worker BF16 reduced-precision disable"
"""


def sha(data):
    return hashlib.sha256(data).hexdigest()


def router_identity():
    """The router parent from its lock, build receipt, gate result and retained image inspection."""
    raw = (ROOT / ROUTER_LOCK).read_bytes()
    router = json.loads(raw)
    receipt = json.loads((ROOT / ROUTER_RECEIPT).read_text())
    if receipt['lock_sha256'] != sha(raw):
        raise RuntimeError('Router build receipt names a different router lock')
    build = ROOT / 'receipts' / Path(receipt['directory']).name
    image = receipt['image_id']
    if (build / 'BUILD-OK').read_text().strip() != image:
        raise RuntimeError('Router build gates did not pass for this image')
    inspect = json.loads((build / 'image-inspect.json').read_text())[0]
    labels = inspect['Config']['Labels']
    if (inspect['Id'].removeprefix('sha256:') != image
            or labels.get('local-inference.ds41.diagnostic.kind') != 'router-stage-release-candidate'
            or labels.get('local-inference.ds41.diagnostic.lock.sha256') != sha(raw)
            or any(labels.get(c + '.source-tree') != t for c, t in router['trees'].items())):
        raise RuntimeError('Router image labels do not match its lock')
    return router, sha(raw), image


def router_vllm_files():
    """Router candidate vLLM sources, rebuilt exactly as claude_prepare_decision_row.vllm_tree_after does."""
    import prepare as runtime_prepare
    from contracts import git_tree, manifest
    router = json.loads((ROOT / ROUTER_LOCK).read_text())
    ring = json.loads((ROOT / 'ring-fix.lock.json').read_text())
    progress = json.loads((ROOT / 'engram-progress-vllm.lock.json').read_text())
    files = runtime_prepare.patched_vllm(runtime_prepare.VLLM)
    for path, source, expected in [(ring['source_path'], 'ring-fix-sparse_mla.py', ring['output_sha256'])] + [
            (p, t['source'], t['output_sha256']) for p, t in progress['targets'].items()]:
        data = (ROOT / source).read_bytes()
        if sha(data) != expected:
            raise RuntimeError('vLLM reconstruction input drift: ' + source)
        files[path] = (files[path][0], data)
    if manifest(files) != router['after']['vllm'] or git_tree(files) != router['trees']['vllm']:
        raise RuntimeError('Router candidate vLLM reconstruction differs')
    return files


def tested_sources():
    """The two target files, required to equal the precision capture lock's tested outputs."""
    precision = json.loads((ROOT / PRECISION_LOCK).read_text())
    changes = {}
    for path, source in SOURCES.items():
        data = (ROOT / source).read_bytes()
        entry = precision['targets']['vllm/' + path]
        if sha(data) != entry['output_sha256']:
            raise RuntimeError('Release source differs from the tested precision target: ' + source)
        changes[path] = data
    return changes, precision


def release(files=None):
    """(before files, after files) of the vLLM component; b12x is the router's unchanged."""
    from contracts import git_tree
    before = files if files is not None else router_vllm_files()
    changes, precision = tested_sources()
    if sha(before[WORKER][1]) != precision['targets']['vllm/' + WORKER]['input_sha256']:
        raise RuntimeError('Router worker is not the precision preimage')
    if HELPER in before or any(p in before for p in CAPTURE_PATHS):
        raise RuntimeError('Router parent unexpectedly carries the helper or capture instrumentation')
    after = dict(before)
    after[WORKER] = (before[WORKER][0], changes[WORKER])
    after[HELPER] = ('100644', changes[HELPER])
    git_tree(after)
    return before, after


def main():
    from contracts import git_tree, manifest
    router, router_sha, image = router_identity()
    before, after = release()
    for name, _ in GATES:
        if router['inputs'].get(name) != sha((ROOT / name).read_bytes()):
            raise RuntimeError('Gate differs from the router build: ' + name)
    for name in GATE_DATA:
        if router['inputs'].get(name) != sha((ROOT / name).read_bytes()):
            raise RuntimeError('Gate data differs from the router build: ' + name)
    precision_raw = (ROOT / PRECISION_LOCK).read_bytes()
    trees = {'vllm': git_tree(after), 'b12x': router['trees']['b12x']}
    copy = ' '.join(sorted(PACKAGED) + [STEM + '.lock.json'])
    (ROOT / ('Dockerfile.' + STEM)).write_text(DOCKERFILE.format(
        short=image[:12], base=image, copy=copy, install=INSTALL_DIR, kind=KIND, base_lock=router_sha,
        precision_lock=sha(precision_raw), vllm=trees['vllm'], b12x=trees['b12x'], status=STATUS))
    inputs = sorted(PACKAGED)
    lock = {'schema': 'ds41-precision-release-v1', 'kind': KIND, 'status': STATUS,
            'base_image_id': image, 'base_kind': 'router-stage-release-candidate',
            'base_lock': ROUTER_LOCK, 'base_lock_sha256': router_sha, 'base_trees': router['trees'],
            'base_install_dir': '/opt/ds41-router-release', 'precision_lock_sha256': sha(precision_raw),
            'before': {'vllm': manifest(before), 'b12x': router['after']['b12x']},
            'after': {'vllm': manifest(after), 'b12x': router['after']['b12x']},
            'trees': trees,
            'targets': {path: {'source': SOURCES[path], 'input_sha256': (sha(before[path][1]) if path in before else None),
                               'output_sha256': sha(after[path][1])} for path in SOURCES},
            'capture_paths_absent': list(CAPTURE_PATHS),
            'install_dir': INSTALL_DIR, 'install_pass': INSTALL_PASS, 'smoke_pass': SMOKE_PASS,
            'gates': [[g, m] for g, m in GATES], 'gate_data': list(GATE_DATA),
            'helper_module': 'vllm.v1.worker.ds41_precision', 'apply_marker': 'DS41-PRECISION-APPLIED',
            'inputs': {name: sha((ROOT / name).read_bytes()) for name in inputs}}
    lock['cache_fingerprint'] = 'ds41-precision-release-' + sha(json.dumps(trees, sort_keys=True).encode())[:20]
    raw = json.dumps(lock, sort_keys=True, indent=2) + '\n'
    (ROOT / (STEM + '.lock.json')).write_text(raw)
    (ROOT / (STEM + '.ignore')).write_text('**\n' + ''.join('!' + n + '\n' for n in inputs + [STEM + '.lock.json']))
    print('PRECISION-RELEASE-PREPARED', sha(raw.encode()), json.dumps(trees, sort_keys=True), flush=True)


if __name__ == '__main__':
    main()
