"""Render deployment examples and parameter tables from the profile registry."""

from __future__ import annotations

import argparse
import json

import yaml

from runtime.launcher import ROOT, resolve


def compose(
    identifier: str,
    *,
    image: str = "${LIL_IMAGE:?Set a profile-enabled image}",
    hardware: str = "rtx-pro-6000-pcie",
    tp: int | None = None,
    mode: str | None = None,
) -> dict:
    overrides = []
    if tp is not None:
        overrides.extend(["--tensor-parallel-size", str(tp)])
    if mode is not None:
        overrides.extend(["--mode", mode])
    plan = resolve(identifier, hardware, env={}, argv=overrides)
    tp = plan.values["tensor-parallel-size"]
    result = {
        "name": identifier,
        "services": {
            "model": {
                "image": image,
                "init": True,
                "network_mode": "host",
                "ipc": "host",
                "restart": "no",
                "entrypoint": ["/usr/local/bin/lil-serve"],
                "command": ["--profile", identifier, "--hardware", hardware],
                "environment": {
                    "MODEL": "${MODEL:-" + plan.values["model"] + "}",
                    "HOST": "${HOST:-0.0.0.0}",
                    "PORT": "${PORT:-8000}",
                    "TP": str(tp),
                    "DCP": "${DCP:-1}",
                    "SPECULATOR": "${SPECULATOR:-" + plan.values["mode"] + "}",
                },
                "volumes": [
                    "model-cache:/root/.cache/huggingface",
                    "runtime-cache:/cache",
                ],
                "deploy": {
                    "resources": {
                        "reservations": {
                            "devices": [
                                {
                                    "driver": "nvidia",
                                    "device_ids": [
                                        "${GPU" + str(n) + ":-" + str(n) + "}"
                                        for n in range(tp)
                                    ],
                                    "capabilities": ["gpu"],
                                }
                            ]
                        }
                    }
                },
            }
        },
        "volumes": {"model-cache": {}, "runtime-cache": {}},
    }
    if identifier == "ds41-flash":
        result["services"]["model"]["ulimits"] = {"memlock": {"soft": -1, "hard": -1}}
        # The published Engram disk path uses io_uring, blocked by Docker's default seccomp profile.
        result["services"]["model"]["security_opt"] = ["seccomp=unconfined"]
    return result


def parameter_table() -> str:
    lines = [
        "| Model profile | TP / DCP | Mode / drafts | Scheduler tokens | OMP | Attention / MoE / dense | Graph cap |",
        "|---|---|---|---:|---:|---|---:|",
    ]
    for path in sorted((ROOT / "profiles").glob("*.yaml")):
        if path.stem == "common":
            continue
        plan = resolve(path.stem, "rtx-pro-6000-pcie", env={})
        v = plan.values
        depth = v.get("speculative-config", {}).get("num_speculative_tokens", 0)
        backends = " / ".join(
            v.get(key, "native")
            for key in ("attention-backend", "moe-backend", "linear-backend")
        )
        lines.append(
            f"| `{path.stem}` | {v['tensor-parallel-size']} / {v['decode-context-parallel-size']} | {v['mode']} / {depth} | {v['max-num-batched-tokens']} | {plan.environment['OMP_NUM_THREADS']} | {backends} | {v['max-cudagraph-capture-size']} |"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("format", choices=["compose", "table", "plan"])
    parser.add_argument("--profile", default="glm53-flash")
    parser.add_argument("--hardware", default="rtx-pro-6000-pcie")
    parser.add_argument("--image", default="${LIL_IMAGE:?Set a profile-enabled image}")
    parser.add_argument("--tp", type=int)
    parser.add_argument("--mode")
    args = parser.parse_args()
    if args.format == "compose":
        print(
            "# Generated by python -m runtime.generate compose; requires a profile-enabled image."
        )
        print(
            yaml.safe_dump(
                compose(
                    args.profile,
                    image=args.image,
                    hardware=args.hardware,
                    tp=args.tp,
                    mode=args.mode,
                ),
                sort_keys=False,
            ),
            end="",
        )
    elif args.format == "table":
        print(parameter_table(), end="")
    else:
        print(
            json.dumps(resolve(args.profile, args.hardware, env={}).public(), indent=2)
        )


if __name__ == "__main__":
    main()
